Update auto reconnect article
altmp/altv-docs pull request #103
Opened 2022-03-19 16:33 UTC by YannBcf

Fix few things

- useless promise returns, as an async function is returning a promise already
- ERROR status check, otherwise it would throw an error
- timeout context binding in the typescript example

This pr also renames the functions in the 3 languages code snippet to be more concise at what its doing

2022-03-23 09:40 UTC, Lhoerion requested changes
Overally ok, just some details need to be perfected

2022-03-23 09:40 UTC, Lhoerion commented on articles/auto_reconnect.md
> +        return "ERROR";
In my perspective such message would indicate, that `ERROR` comes from response, not from failure. I'd expect here a throw or `null`

2022-03-23 09:40 UTC, Lhoerion commented on articles/auto_reconnect.md
> +type STATUS =
Make it a const enum

2022-03-23 09:40 UTC, Lhoerion commented on articles/auto_reconnect.md
> +        setTimeout(() => this.connectLocalClient(), 2500);
Make delay a const value

2022-03-23 09:40 UTC, Lhoerion commented on articles/auto_reconnect.md
> +        return response.text() as unknown as STATUS;
These castings will be obsolete once `STATUS` will become an const enum

2022-03-23 09:40 UTC, Lhoerion commented on articles/auto_reconnect.md
> +        private async Task<string> GetLocalClientStatus()
Create enum for statuses

2022-04-12 13:00 UTC, YannBcf commented on articles/auto_reconnect.md
> +        return response.text() as unknown as STATUS;
They are still necessary apparently, otherwise ts yell at me

2022-04-12 15:48 UTC, Unnvaldr commented on articles/auto_reconnect.md
> +        return response.text() as unknown as STATUS;
You've a mistake there then, because you try to cast `Promise<string>` to `STATUS`

2022-04-12 15:49 UTC, Unnvaldr commented on articles/auto_reconnect.md
> +const enum STATUS {
Enumeration name should be converted to PascalCase

2022-04-12 21:30 UTC, zziger commented on articles/auto_reconnect.md
> +        private async Task<string> GetLocalClientStatus()
In C# you can't really have an enum with string values. The only option would be making a normal enum and converting the string into it either by having a switch/dictionary/etc, or by using Enum.Parse. Idk if we would really want it here XD

2022-04-13 19:29 UTC, Unnvaldr commented on articles/auto_reconnect.md
> +        private async Task<string> GetLocalClientStatus()
Not directly supported, but we can do it via extending `Enumeration` class. Still better than having none at all in my opinion

2022-06-30 09:58 UTC, C0kkie commented
https://github.com/altmp/altv-docs/commit/e3681704b9c5f7691ceded6d3d0c96a39ab9f601

2022-06-30 09:58 UTC, closed without merging