Add Linux information to CEF article
altmp/altv-docs pull request #104
Opened 2022-03-23 13:16 UTC by ZackaryH8

2022-03-23 13:16 UTC, ZackaryH8 commented
Might be irrelevant if the actual issue is fixed [here](https://github.com/altmp/altv-issues/issues/1412)

2022-03-23 16:00 UTC, Lhoerion approved these changes
Nicely done :)

2022-03-23 17:36 UTC, lolsniperftw commented
Note that even if the issue is fixed by the devs then only the part with copying files becomes irrelevent.
The part about running the game using Windows of Steam, etc ,,, will still be relevant.

2022-03-24 18:05 UTC, Lhoerion commented
@ZackaryH8 Inner talks had taken place about where to put this section and we came to the conclusion that Troubleshooting article seems like a more appropriate spot. However, since CEF article is actually connected to this particular remark, I'd recommend to leave a note there with a proper reference link

2022-03-24 18:06 UTC, Lhoerion requested changes
@ZackaryH8 Inner talks had taken place about where to put this section and we came to the conclusion that Troubleshooting article seems like a more appropriate spot. However, since CEF article is actually connected to this particular remark, I'd recommend to leave a note there with a proper reference link

2022-03-24 18:53 UTC, ZackaryH8 commented
So to clarify I will move this information to troubleshooting and add a link to cef page to the troubleshooting page?

2022-03-24 18:55 UTC, Lhoerion commented
First part correct, second one more like "add a link in cef page to the troubleshooting page"

2022-03-25 13:44 UTC, ZackaryH8 commented
Let me know if you need to do anything else

2022-03-26 12:18 UTC, Lhoerion requested changes

2022-03-26 12:18 UTC, Lhoerion commented on articles/troubleshooting/client.md
> +###### Linux
Change to `h4`, so it'll be marked for anchoring. Also title more like `Webview not rendering on Linux`. Then you can link it like `./troubleshooting/client.md#webview-not-rendering-on-linux`

2022-04-02 07:16 UTC, Unnvaldr approved these changes

2022-04-02 07:16 UTC, merged