created voice.cfg
altmp/altv-docs pull request #82
Opened 2021-12-08 14:35 UTC by cmdflow

2021-12-08 15:01 UTC, C0kkie commented
You miss a entry in the toc.yml

2021-12-08 15:04 UTC, C0kkie requested changes

2021-12-08 15:04 UTC, C0kkie commented on articles/configs/voice.md
> +The `voice.cfg` file is needed if you are running external altv-voice-server. The settings for using it on same machine as altv-server are:
You miss the header on the top like

``# The `voice.cfg` configuration file``

2021-12-08 15:55 UTC, C0kkie commented
What about a explanation to the config entries like the server.cfg

2021-12-08 16:01 UTC, cmdflow commented
Feel free to do so. I don't explain what i don't understand. No idea what was the intention of all those parameters and how they are working internally. Just wanted to help other ppl not to probe against 100 versions of config due to lack of good explanation in docs ;)

2021-12-08 16:08 UTC, C0kkie commented
Without a explanation it doesnt make sense to add it

2021-12-08 16:09 UTC, cmdflow commented
Well then delete the pull request. so the next one has to ask again if its 127.x or 0.x - i cant explain it. i would if i could

2021-12-11 14:39 UTC, DurtyFree commented
@cmdflow thx for the efforts, we understand the lack of documentation here and will try to add some detailed documentation for this soon.

Until then you can follow up in #83 
Closing this for now, thx:)

2021-12-11 14:39 UTC, closed without merging